import { PrismaClient } from "@prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { enrichLeadScores, type ScorableLead } from "../lib/scoring";

const adapter = new PrismaBetterSqlite3({
  url: process.env.DATABASE_URL ?? "file:./dev.db",
});

const prisma = new PrismaClient({ adapter });

type SeedLead = ScorableLead & {
  companyName: string;
  category: string;
  website: string;
  location: string;
  contactName: string;
  contactTitle: string;
  contactEmail: string;
  linkedinUrl?: string;
  warmIntroSource?: string;
  notes: string;
  estimatedBudget: string;
  remoteFriendly: boolean;
  stage: string;
  nextAction: string;
  lastContactedDate?: Date;
  followUpDate?: Date;
  personalizedAngle: string;
  objectionRisk: string;
  confidenceLevel: string;
};

const leads: SeedLead[] = [
  {
    companyName: "Northstar Heritage Office",
    category: "Family Office",
    website: "https://example.com/northstar",
    location: "New York, NY",
    contactName: "Avery Mitchell",
    contactTitle: "Principal",
    contactEmail: "contact@example.com",
    warmIntroSource: "Former fintech founder",
    notes: "Interested in next-gen education for rising family members and practical AI workflows for investment learning.",
    estimatedBudget: "$10K-$20K/month",
    remoteFriendly: true,
    stage: "Researched",
    nextAction: "Ask warm source for intro to principal",
    followUpDate: daysFromNow(2),
    personalizedAngle: "next-gen investment education, decision quality, and practical AI tools for family learning",
    objectionRisk: "May prefer trusted referrals before a direct pitch.",
    confidenceLevel: "High",
    abilityToPay: 5,
    fitWithMyBackground: 5,
    needForAiProductHelp: 4,
    relevanceToLcs: 5,
    relevanceToDecisionIntelligence: 5,
    familyOfficeOrWealthFit: 5,
    institutionalEducationFit: 3,
    accessibilityOfDecisionMaker: 4,
    warmIntroStrength: 4,
    urgency: 4,
    remoteOrFractionalFit: 5,
  },
  {
    companyName: "Harborline Wealth Partners",
    category: "RIA / Wealth Manager",
    website: "https://example.com/harborline",
    location: "Remote / Boston",
    contactName: "Jordan Ellis",
    contactTitle: "Head of Client Experience",
    contactEmail: "contact@example.com",
    notes: "RIA wants more differentiated investor education and client-facing AI learning tools.",
    estimatedBudget: "$5K-$10K/month",
    remoteFriendly: true,
    stage: "Scored",
    nextAction: "Draft email around AI financial literacy consultant offer",
    followUpDate: daysFromNow(4),
    personalizedAngle: "client education that connects macro events, confidence, prediction, and portfolio learning",
    objectionRisk: "Compliance review could slow pilot scope.",
    confidenceLevel: "Medium-high",
    abilityToPay: 4,
    fitWithMyBackground: 5,
    needForAiProductHelp: 4,
    relevanceToLcs: 5,
    relevanceToDecisionIntelligence: 4,
    familyOfficeOrWealthFit: 5,
    institutionalEducationFit: 3,
    accessibilityOfDecisionMaker: 3,
    warmIntroStrength: 2,
    urgency: 3,
    remoteOrFractionalFit: 5,
  },
  {
    companyName: "LedgerPath",
    category: "Fintech Startup",
    website: "https://example.com/ledgerpath",
    location: "San Francisco, CA",
    contactName: "Sam Rivera",
    contactTitle: "CEO",
    contactEmail: "contact@example.com",
    notes: "Seed-stage fintech needs product clarity around AI-assisted planning workflows.",
    estimatedBudget: "$10K-$20K/month",
    remoteFriendly: true,
    stage: "Outreach Drafted",
    nextAction: "Send founder-to-founder cold email",
    followUpDate: daysFromNow(3),
    personalizedAngle: "turning ambiguous AI product ideas into shipped workflows and customer-facing features",
    objectionRisk: "Runway sensitivity.",
    confidenceLevel: "High",
    abilityToPay: 4,
    fitWithMyBackground: 5,
    needForAiProductHelp: 5,
    relevanceToLcs: 4,
    relevanceToDecisionIntelligence: 4,
    familyOfficeOrWealthFit: 2,
    institutionalEducationFit: 2,
    accessibilityOfDecisionMaker: 4,
    warmIntroStrength: 1,
    urgency: 5,
    remoteOrFractionalFit: 5,
  },
  {
    companyName: "ModelForge AI",
    category: "AI Startup",
    website: "https://example.com/modelforge",
    location: "Remote",
    contactName: "Priya Shah",
    contactTitle: "Founder",
    contactEmail: "contact@example.com",
    notes: "Team has strong technical base but needs sharper product packaging and GTM workflow demos.",
    estimatedBudget: "$7.5K/month",
    remoteFriendly: true,
    stage: "Found",
    nextAction: "Research current product motion and founder posts",
    followUpDate: daysFromNow(6),
    personalizedAngle: "shipping concrete AI workflows from vague strategy and model capability claims",
    objectionRisk: "May see product help as internal founder responsibility.",
    confidenceLevel: "Medium",
    abilityToPay: 3,
    fitWithMyBackground: 5,
    needForAiProductHelp: 5,
    relevanceToLcs: 3,
    relevanceToDecisionIntelligence: 4,
    familyOfficeOrWealthFit: 1,
    institutionalEducationFit: 2,
    accessibilityOfDecisionMaker: 4,
    warmIntroStrength: 1,
    urgency: 4,
    remoteOrFractionalFit: 5,
  },
  {
    companyName: "CivicTrust Credit Union",
    category: "Credit Union",
    website: "https://example.com/civictrust",
    location: "Atlanta, GA",
    contactName: "Morgan Lee",
    contactTitle: "VP, Community Impact",
    contactEmail: "contact@example.com",
    warmIntroSource: "Community banking advisor",
    notes: "Potential financial literacy pilot for young members and workforce partners.",
    estimatedBudget: "$20K pilot",
    remoteFriendly: true,
    stage: "Sent",
    nextAction: "Follow up with institutional pilot blurb",
    lastContactedDate: daysFromNow(-6),
    followUpDate: daysFromNow(1),
    personalizedAngle: "AI-enabled financial literacy that teaches decision-making under uncertainty",
    objectionRisk: "Needs executive sponsor and compliance-safe messaging.",
    confidenceLevel: "Medium-high",
    abilityToPay: 4,
    fitWithMyBackground: 5,
    needForAiProductHelp: 4,
    relevanceToLcs: 5,
    relevanceToDecisionIntelligence: 5,
    familyOfficeOrWealthFit: 3,
    institutionalEducationFit: 5,
    accessibilityOfDecisionMaker: 3,
    warmIntroStrength: 3,
    urgency: 3,
    remoteOrFractionalFit: 4,
  },
  {
    companyName: "Metro Skills Institute",
    category: "HBCU / Workforce Program",
    website: "https://example.com/metroskills",
    location: "Baltimore, MD",
    contactName: "Dr. Casey Brooks",
    contactTitle: "Director of Innovation",
    contactEmail: "contact@example.com",
    notes: "Exploring applied AI curriculum and employer-aligned finance education.",
    estimatedBudget: "$15K-$25K pilot",
    remoteFriendly: true,
    stage: "Call Booked",
    nextAction: "Prepare discovery agenda for calibration workshop",
    lastContactedDate: daysFromNow(-2),
    followUpDate: daysFromNow(5),
    personalizedAngle: "teaching decision-making under uncertainty through prediction, calibration, and applied AI",
    objectionRisk: "Academic procurement timing.",
    confidenceLevel: "High",
    abilityToPay: 4,
    fitWithMyBackground: 5,
    needForAiProductHelp: 4,
    relevanceToLcs: 5,
    relevanceToDecisionIntelligence: 5,
    familyOfficeOrWealthFit: 1,
    institutionalEducationFit: 5,
    accessibilityOfDecisionMaker: 4,
    warmIntroStrength: 2,
    urgency: 4,
    remoteOrFractionalFit: 4,
  },
  {
    companyName: "FutureProof Learning",
    category: "Edtech Company",
    website: "https://example.com/futureproof",
    location: "Chicago, IL",
    contactName: "Taylor Nguyen",
    contactTitle: "Chief Product Officer",
    contactEmail: "contact@example.com",
    notes: "Edtech platform wants AI differentiation beyond chatbots.",
    estimatedBudget: "$5K-$10K/month",
    remoteFriendly: true,
    stage: "Researched",
    nextAction: "Send product strategy sprint email",
    followUpDate: daysFromNow(7),
    personalizedAngle: "using prediction and calibration loops to make learning outcomes measurable",
    objectionRisk: "May already have internal curriculum team.",
    confidenceLevel: "Medium",
    abilityToPay: 3,
    fitWithMyBackground: 4,
    needForAiProductHelp: 4,
    relevanceToLcs: 5,
    relevanceToDecisionIntelligence: 5,
    familyOfficeOrWealthFit: 1,
    institutionalEducationFit: 4,
    accessibilityOfDecisionMaker: 3,
    warmIntroStrength: 1,
    urgency: 3,
    remoteOrFractionalFit: 4,
  },
  {
    companyName: "LaunchBay Studio",
    category: "Venture Studio",
    website: "https://example.com/launchbay",
    location: "Miami, FL",
    contactName: "Riley Stone",
    contactTitle: "Managing Partner",
    contactEmail: "contact@example.com",
    notes: "Studio builds fintech and AI concepts and may need operator-in-residence support.",
    estimatedBudget: "$10K/month",
    remoteFriendly: true,
    stage: "Found",
    nextAction: "Find portfolio fit and ask for intro",
    followUpDate: daysFromNow(8),
    personalizedAngle: "turning early venture concepts into shipped prototypes and pilotable product wedges",
    objectionRisk: "May prefer equity-heavy structure.",
    confidenceLevel: "Medium",
    abilityToPay: 4,
    fitWithMyBackground: 5,
    needForAiProductHelp: 4,
    relevanceToLcs: 3,
    relevanceToDecisionIntelligence: 3,
    familyOfficeOrWealthFit: 2,
    institutionalEducationFit: 2,
    accessibilityOfDecisionMaker: 3,
    warmIntroStrength: 2,
    urgency: 4,
    remoteOrFractionalFit: 5,
  },
  {
    companyName: "Catalyst Alpha Accelerator",
    category: "Accelerator",
    website: "https://example.com/catalystalpha",
    location: "Remote",
    contactName: "Jamie Carter",
    contactTitle: "Program Director",
    contactEmail: "contact@example.com",
    notes: "Accelerator supports fintech and AI cohorts that need product strategy mentorship.",
    estimatedBudget: "$3K workshop",
    remoteFriendly: true,
    stage: "Nurture",
    nextAction: "Offer workshop for next cohort",
    followUpDate: daysFromNow(14),
    personalizedAngle: "helping cohort founders move from AI claims to credible workflows and prototypes",
    objectionRisk: "Budget may be workshop-sized.",
    confidenceLevel: "Medium",
    abilityToPay: 2,
    fitWithMyBackground: 5,
    needForAiProductHelp: 4,
    relevanceToLcs: 3,
    relevanceToDecisionIntelligence: 3,
    familyOfficeOrWealthFit: 1,
    institutionalEducationFit: 3,
    accessibilityOfDecisionMaker: 4,
    warmIntroStrength: 2,
    urgency: 3,
    remoteOrFractionalFit: 5,
  },
  {
    companyName: "SignalMark Markets",
    category: "Prediction Market Company",
    website: "https://example.com/signalmark",
    location: "Remote / DC",
    contactName: "Dana Kim",
    contactTitle: "Head of Product",
    contactEmail: "contact@example.com",
    notes: "Prediction market company looking at education and calibration layers.",
    estimatedBudget: "$7.5K/month",
    remoteFriendly: true,
    stage: "Proposal Sent",
    nextAction: "Follow up on calibration lab proposal",
    lastContactedDate: daysFromNow(-8),
    followUpDate: daysFromNow(0),
    personalizedAngle: "bringing calibration scoring and prediction-based learning into a customer education layer",
    objectionRisk: "May frame this as feature work instead of consulting.",
    confidenceLevel: "High",
    abilityToPay: 4,
    fitWithMyBackground: 5,
    needForAiProductHelp: 4,
    relevanceToLcs: 5,
    relevanceToDecisionIntelligence: 5,
    familyOfficeOrWealthFit: 2,
    institutionalEducationFit: 3,
    accessibilityOfDecisionMaker: 4,
    warmIntroStrength: 3,
    urgency: 4,
    remoteOrFractionalFit: 5,
  },
  {
    companyName: "AtlasVest",
    category: "Investment Platform",
    website: "https://example.com/atlasvest",
    location: "Charlotte, NC",
    contactName: "Chris Martin",
    contactTitle: "Product Lead",
    contactEmail: "contact@example.com",
    notes: "Investment app wants stronger user learning loops tied to macro events.",
    estimatedBudget: "$5K-$10K/month",
    remoteFriendly: true,
    stage: "Followed Up",
    nextAction: "Send concise proposal blurb",
    lastContactedDate: daysFromNow(-11),
    followUpDate: daysFromNow(-1),
    personalizedAngle: "macro-to-portfolio learning loops that help users understand uncertainty and confidence",
    objectionRisk: "May be focused on acquisition features this quarter.",
    confidenceLevel: "Medium-high",
    abilityToPay: 4,
    fitWithMyBackground: 5,
    needForAiProductHelp: 3,
    relevanceToLcs: 5,
    relevanceToDecisionIntelligence: 5,
    familyOfficeOrWealthFit: 4,
    institutionalEducationFit: 3,
    accessibilityOfDecisionMaker: 3,
    warmIntroStrength: 2,
    urgency: 3,
    remoteOrFractionalFit: 5,
  },
  {
    companyName: "Bridgewell Wealthtech",
    category: "Wealthtech Platform",
    website: "https://example.com/bridgewell",
    location: "Remote / Denver",
    contactName: "Alex Morgan",
    contactTitle: "VP Product",
    contactEmail: "contact@example.com",
    notes: "Platform sells to advisors and wants AI education modules for end clients.",
    estimatedBudget: "$10K/month",
    remoteFriendly: true,
    stage: "Won",
    nextAction: "Kick off product strategy sprint",
    lastContactedDate: daysFromNow(-1),
    followUpDate: daysFromNow(3),
    personalizedAngle: "advisor-facing AI education modules backed by decision intelligence and calibration concepts",
    objectionRisk: "Need scoped pilot before recurring retainer.",
    confidenceLevel: "High",
    abilityToPay: 4,
    fitWithMyBackground: 5,
    needForAiProductHelp: 5,
    relevanceToLcs: 5,
    relevanceToDecisionIntelligence: 5,
    familyOfficeOrWealthFit: 4,
    institutionalEducationFit: 3,
    accessibilityOfDecisionMaker: 4,
    warmIntroStrength: 4,
    urgency: 4,
    remoteOrFractionalFit: 5,
  },
];

async function main() {
  await prisma.lead.deleteMany();

  for (const lead of leads) {
    const scoring = enrichLeadScores(lead);
    await prisma.lead.create({
      data: {
        ...lead,
        ...scoring,
      },
    });
  }
}

function daysFromNow(days: number) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date;
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
