export type LeadRecord = {
  id: string;
  companyName: string;
  category: string;
  website: string | null;
  location: string | null;
  contactName: string | null;
  contactTitle: string | null;
  contactEmail: string | null;
  linkedinUrl: string | null;
  warmIntroSource: string | null;
  notes: string | null;
  estimatedBudget: string | null;
  urgency: number;
  remoteFriendly: boolean;
  abilityToPay: number;
  fitWithMyBackground: number;
  needForAiProductHelp: number;
  relevanceToLcs: number;
  relevanceToDecisionIntelligence: number;
  familyOfficeOrWealthFit: number;
  institutionalEducationFit: number;
  accessibilityOfDecisionMaker: number;
  warmIntroStrength: number;
  remoteOrFractionalFit: number;
  fitScore: number;
  stage: string;
  nextAction: string | null;
  lastContactedDate: Date | null;
  followUpDate: Date | null;
  suggestedOffer: string | null;
  personalizedAngle: string | null;
  monthlyRevenuePotential: string | null;
  objectionRisk: string | null;
  confidenceLevel: string | null;
  sourceUrl: string | null;
  sourceType: string | null;
  sourceLastScrapedAt: Date | null;
  sourceConfidence: number;
  canonicalUrl: string | null;
  atsProvider: string;
  atsExternalId: string | null;
  atsBoardToken: string | null;
  verificationStatus: string;
  lastVerifiedAt: Date | null;
  lastCheckedAt: Date | null;
  staleDetectedAt: Date | null;
  staleReason: string | null;
  checkFailCount: number;
  priorityLevel: string;
  createdAt: Date;
  updatedAt: Date;
};
